#! /bin/bash
# Launch manpages in PDF Format using Rofi as Menu
var=$(apropos . -s 1 | awk '{print $1}' | sort | rofi -dmenu -p "Enter the utility name" -font "IBM Plex Sans SemiBold 16" -columns 3 -lines 10 -padding 20 -color-window "#330b0d13, #330b0d13, #000b0d13" -color-normal "#440b0d13, #e6e6e6, #440b0d13, #880b0d13, #e6e6e6")
man -Tpdf "$var" > file.pdf
mupdf -I file.pdf 
rm file.pdf
